"""mano de bastones del jugador

Revision ID: 9141089ac8f0
Revises: a478b50a1e57
Create Date: 2026-09-18 12:46:46.971496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Tipos propios usados en las columnas de dinero y tipo de cambio.
# Alembic los referencia como app.shared.money.X al autogenerar, así que el
# paquete tiene que estar importado aquí.
import app.shared.money


# revision identifiers, used by Alembic.
revision: str = '9141089ac8f0'
down_revision: Union[str, Sequence[str], None] = 'a478b50a1e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_hand', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_players', schema=None) as batch_op:
        batch_op.drop_column('club_hand')

    # ### end Alembic commands ###
