"""esquema inicial

Revision ID: a478b50a1e57
Revises: 
Create Date: 2026-09-17 16:36:24.997411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Tipos propios usados en las columnas de dinero y tipo de cambio.
# Alembic los referencia como app.shared.money.X al autogenerar, así que el
# paquete tiene que estar importado aquí.
import app.shared.money


# revision identifiers, used by Alembic.
revision: str = 'a478b50a1e57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_services_code'), ['code'], unique=True)

    op.create_table('course_schedule_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tee', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('slot_capacity', sa.Integer(), nullable=False),
    sa.Column('holes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('contact_name', sa.String(length=180), nullable=True),
    sa.Column('contact_email', sa.String(length=180), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('commission_rate', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False, comment='Porcentaje de participación del hotel sobre venta bruta'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_code'), ['code'], unique=True)

    op.create_table('pga_benefit_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=24), nullable=False),
    sa.Column('value', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pga_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pga_code', sa.String(length=48), nullable=False),
    sa.Column('credential_number', sa.String(length=48), nullable=False),
    sa.Column('professional_name', sa.String(length=180), nullable=False),
    sa.Column('accreditation', sa.String(length=120), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pga_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pga_credentials_credential_number'), ['credential_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pga_credentials_pga_code'), ['pga_code'], unique=True)

    op.create_table('rate_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('holes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('price', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_plans_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_plans_holes'), ['holes'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_plans_modality'), ['modality'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('discount_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=24), nullable=False),
    sa.Column('value', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('applicable_modalities', sa.String(length=255), nullable=True, comment='Lista separada por comas'),
    sa.Column('applicable_holes', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_discount_codes_hotel_id'), ['hotel_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=180), nullable=True, comment='Nombre copiado: si el usuario se borra, la bitácora sigue diciendo quién fue'),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=48), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('expected_cash_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('expected_card_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('expected_transfer_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('expected_total_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash_usd', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('counted_card_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('counted_transfer_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('counted_total_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate_applied', app.shared.money.DecimalRate(precision=10, scale=4), nullable=True),
    sa.Column('difference_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_status'), ['status'], unique=False)

    op.create_table('course_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('tee', sa.String(length=24), nullable=False),
    sa.Column('estimated_players', sa.Integer(), nullable=True),
    sa.Column('blocks_availability', sa.Boolean(), nullable=False, comment='Si es True, las franjas del rango quedan BLOQUEADAS'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_events_event_type'), ['event_type'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_effective_from'), ['effective_from'], unique=False)

    op.create_table('hotel_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reservations_count', sa.Integer(), nullable=False),
    sa.Column('gross_sales', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('pga_discounts', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate_applied', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False),
    sa.Column('commission_amount', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('net_course', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('settled_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotel_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_settlements_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_settlements_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_settlements_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_settlements_status'), ['status'], unique=False)

    op.create_table('tee_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('tee', sa.String(length=24), nullable=False),
    sa.Column('slot_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['course_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_date', 'tee', 'slot_time', name='uq_tee_slot_unico')
    )
    with op.batch_alter_table('tee_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tee_slots_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tee_slots_slot_date'), ['slot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tee_slots_slot_time'), ['slot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_tee_slots_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tee_slots_tee'), ['tee'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=32), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tee_slot_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('holes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('holder_name', sa.String(length=180), nullable=False),
    sa.Column('holder_email', sa.String(length=180), nullable=False),
    sa.Column('holder_phone', sa.String(length=40), nullable=True),
    sa.Column('holder_room', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discount_code_id', sa.Integer(), nullable=True),
    sa.Column('discount_code_applied', sa.String(length=48), nullable=True),
    sa.Column('exchange_rate_applied', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False),
    sa.Column('commission_rate_applied', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False),
    sa.Column('subtotal_green_fees', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_services', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('pga_discount_amount', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('total', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=True),
    sa.Column('qr_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_requested', sa.Boolean(), nullable=False),
    sa.Column('invoice_contact_email', sa.String(length=180), nullable=True),
    sa.Column('invoice_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tee_slot_id'], ['tee_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_folio'), ['folio'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservations_holder_name'), ['holder_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_holder_phone'), ['holder_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_qr_token'), ['qr_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_tee_slot_id'), ['tee_slot_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False, comment='Monto en la moneda original'),
    sa.Column('exchange_rate_applied', app.shared.money.DecimalRate(precision=10, scale=4), nullable=False),
    sa.Column('amount_mxn', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False, comment='Equivalente en MXN al TC aplicado'),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_cash_session_id'), ['cash_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('reservation_companions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_companions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_companions_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('reservation_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('handicap', sa.String(length=12), nullable=True),
    sa.Column('is_holder', sa.Boolean(), nullable=False),
    sa.Column('pga_code', sa.String(length=48), nullable=True),
    sa.Column('credential_number', sa.String(length=48), nullable=True),
    sa.Column('pga_validated', sa.Boolean(), nullable=False),
    sa.Column('pga_validated_by_id', sa.Integer(), nullable=True),
    sa.Column('pga_validated_at', sa.DateTime(), nullable=True),
    sa.Column('pga_discount_applied', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('rate_applied', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('final_rate', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('arrived', sa.Boolean(), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pga_validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_players_pga_code'), ['pga_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_players_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('reservation_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_applied', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('total', app.shared.money.DecimalMoney(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['reservation_players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['additional_services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_services_reservation_id'), ['reservation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_services_reservation_id'))

    op.drop_table('reservation_services')
    with op.batch_alter_table('reservation_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_players_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_players_pga_code'))

    op.drop_table('reservation_players')
    with op.batch_alter_table('reservation_companions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_companions_reservation_id'))

    op.drop_table('reservation_companions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payments_method'))
        batch_op.drop_index(batch_op.f('ix_payments_cash_session_id'))

    op.drop_table('payments')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_tee_slot_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_reservations_qr_token'))
        batch_op.drop_index(batch_op.f('ix_reservations_modality'))
        batch_op.drop_index(batch_op.f('ix_reservations_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_holder_phone'))
        batch_op.drop_index(batch_op.f('ix_reservations_holder_name'))
        batch_op.drop_index(batch_op.f('ix_reservations_folio'))

    op.drop_table('reservations')
    with op.batch_alter_table('tee_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tee_slots_tee'))
        batch_op.drop_index(batch_op.f('ix_tee_slots_status'))
        batch_op.drop_index(batch_op.f('ix_tee_slots_slot_time'))
        batch_op.drop_index(batch_op.f('ix_tee_slots_slot_date'))
        batch_op.drop_index(batch_op.f('ix_tee_slots_event_id'))

    op.drop_table('tee_slots')
    with op.batch_alter_table('hotel_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_settlements_status'))
        batch_op.drop_index(batch_op.f('ix_hotel_settlements_period_start'))
        batch_op.drop_index(batch_op.f('ix_hotel_settlements_period_end'))
        batch_op.drop_index(batch_op.f('ix_hotel_settlements_hotel_id'))

    op.drop_table('hotel_settlements')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_effective_from'))

    op.drop_table('exchange_rates')
    with op.batch_alter_table('course_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_course_events_event_date'))

    op.drop_table('course_events')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_cash_sessions_session_date'))

    op.drop_table('cash_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_codes_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_discount_codes_code'))

    op.drop_table('discount_codes')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_plans_modality'))
        batch_op.drop_index(batch_op.f('ix_rate_plans_holes'))
        batch_op.drop_index(batch_op.f('ix_rate_plans_category'))

    op.drop_table('rate_plans')
    with op.batch_alter_table('pga_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pga_credentials_pga_code'))
        batch_op.drop_index(batch_op.f('ix_pga_credentials_credential_number'))

    op.drop_table('pga_credentials')
    op.drop_table('pga_benefit_config')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_code'))

    op.drop_table('hotels')
    op.drop_table('course_schedule_config')
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_services_code'))

    op.drop_table('additional_services')
    # ### end Alembic commands ###
